import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Sidebar do Portal do Fornecedor - instância de docs separada do Manual
  // do ERP (pasta supplier-portal-docs/, roteada em /supplier-portal).
  // As páginas ficam soltas (sem categoria "Portal do Fornecedor" própria
  // dentro do sidebar) porque o link de topo já dá esse contexto.
  supplierPortalSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
