import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  // Um único sidebar, gerado a partir de tudo que existir em docs/, na mesma
  // ordem em que os itens aparecem no menu lateral do próprio ERP: Sobre,
  // Pacotes comerciais, e cada módulo do sistema (Administrativo, Recursos
  // Humanos, ...), cada um com suas páginas de controller por dentro.
  manualSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
